### ISSUE TITLE
Using Yarn workspaces results in: Error: method not available in web

### ISSUE THREAD

**Issue by czabaj** [capacitor-community/barcode-scanner#57] opened 2021-07-08 08:36 UTC
**Describe the bug**
All methods yield just `Error: method not available in web`.

**To Reproduce**
Use ~~any~~ methods of the plugin.
EDIT: I'm using just `prepare`, `hide/show-Background` and `startScan` methods.

**Version**

I'm using Capacitor.js@2.4.7 and @capacitor-community/barcode-scanner@1.2.1, here is the full list of `yarn cap doctor`

```
💊   Capacitor Doctor  💊 

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 10 Capacitor plugins for ios:
    @capacitor-community/barcode-scanner (1.2.1)
    capacitor-dark-mode (1.0.5)
    capacitor-plugin-ios-swipe-back (1.0.3)
    capacitor-rate-app (0.1.1)
    capacitor-secure-storage-plugin (0.5.0)
    cordova-plugin-appcenter-crashes (0.5.1)
    cordova-plugin-appcenter-shared (0.5.1)
    cordova-plugin-fingerprint-aio (4.0.2)
    cordova-plugin-inappbrowser (5.0.1-dev)
    onesignal-cordova-plugin (2.11.3)
[success] iOS looking great! 👌
```

**Desktop (please complete the following information):**

I'm using Yarn@1 with workspaces feature in a monorepo.

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 439.66 MB / 32.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Browsers:
    Brave Browser: 89.1.21.77
    Chrome: 91.0.4472.114
    Edge: 91.0.864.54
    Firefox: 85.0.2
    Safari: 14.1.1
```

**Smartphone (please complete the following information):**

Tested on one physical device

- Device: Samsung SM-J330F
- OS: Android 8.0
- WebView implementation with Chrome 91.0.4472.120

And on an Apple simulator

- Device: iPhone 11
- OS: iOS 14.5

And on an Android emulator

- Device: Pixel 3
- OS: Android 11

**Additional context**
I read the logs for anything "barcode" related but no trace of warning/error. I also double-checked the setup and all seems to be OK.

**Comment by Saqib92** [comment] 2021-07-09 06:41
i think this plugin only works for Android / IOS. and web is not supported yet.

**Comment by pumpkin-zbh** [comment] 2021-07-10 02:19
same question.

**Comment by tafelnl** [comment] 2021-07-10 07:27
Web is not supported indeed. But it looks like you are trying to run it in a native environment anyway.

Did you succeed in installing and running any other plugin? 

You can check #30 which is a similar issue. If you still encounter problems, would you be so kind the share a repo to reproduce this issue, so we can take a closer look.

**Comment by czabaj** [comment] 2021-07-12 02:53
Yes, I test the mobile implementation, the usage of the web implementation is simply the issue here. I've read the #30 and tried to reinstall the project many times - still no success. Might the Yarn workspaces be an issue? I might try no-hoist the package 🤔 

Anyway, just tested the [PhoneGap Plugin BarcodeScanner](https://github.com/phonegap/phonegap-plugin-barcodescanner) and it works like a charm. Unfortunately, the project is archived, so I hoped to use your code which targets capacitor.js specifically and is maintained.

I could not share the code with you, as it is treated as confidential, but I can share the AndroidManifest. But the plugin does not work on iOS either and the setup there is minimal.

```xml
<?xml
    version="1.0"
    encoding="utf-8"
?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="cz.mallpay"
>
    <supports-screens
        android:largeScreens="true"
        android:largestWidthLimitDp="600"
        android:normalScreens="true"
        android:smallScreens="true"
        android:xlargeScreens="false"
    />
    <application
        android:allowBackup="false"
        android:fullBackupOnly="false"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:networkSecurityConfig="@xml/network_security_config"
        android:roundIcon="@mipmap/ic_launcher"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true"
    >
        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name="cz.mallpay.MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
        >
            <intent-filter>
                <action
                    android:name="android.intent.action.MAIN"
                />
                <category
                    android:name="android.intent.category.LAUNCHER"
                />
            </intent-filter>
        </activity>
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true"
        >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"
            />
        </provider>
    </application>
    <!-- Permissions -->
    <uses-permission
        android:name="android.permission.INTERNET"
    />
    <!-- Camera, Photos, input file -->
    <uses-permission
        android:name="android.permission.CAMERA"
    />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
    />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    />
    <!-- Network API -->
    <uses-permission
        android:name="android.permission.ACCESS_NETWORK_STATE"
    />
    <uses-sdk
        tools:overrideLibrary="com.google.zxing.client.android"
    />
</manifest>
```

**Comment by tafelnl** [comment] 2021-07-12 05:33
Would you be able to, instead of sharing the whole repo, share a minimal reproduction repo (with any confidential code stripped out)

**Comment by czabaj** [comment] 2021-07-12 12:42
Sorry, this demands at least an hour to set up and test that it (don't) work and I'm short on time. I switched to the [PhoneGap Plugin BarcodeScanner](https://github.com/phonegap/phonegap-plugin-barcodescanner) which works nicely. I would love to help you with the issue, but I cannot promise you any help in the foreseen period of time, so I rather not promise anything.

I thought the problem will be some obvious trifle but it is too difficult to resolve. Feel free to close the issue if you want.

**Comment by tafelnl** [comment] 2021-07-13 09:25
My best guess it would be that the Yarn workspaces are the issue here indeed. I am not sure what exactly could be going wrong. If anyone every encounters a similar problem and finds a solution, please share :)

**Comment by mozolev** [comment] 2021-07-21 00:28
> My best guess it would be that the Yarn workspaces are the issue here indeed. I am not sure what exactly could be going wrong. If anyone every encounters a similar problem and finds a solution, please share :)

I also ran into this issue, however, we do not use Yarn in our project😕

**Comment by tafelnl** [comment] 2021-07-21 10:28
@mozolev It is very likely that this issue is being caused by some configuration issue. Either being yarn or something else.

That means it is probably not caused by this library itself. Steps on resolving this issue:

- First check that you are using the correct version: https://github.com/capacitor-community/barcode-scanner#note-on-supported-capacitor-versions
- Try installing any other plugin without an actual web implementation and check if that works.
- Create a whole new clean project and install this plugin, then check if it works
- If, after debugging, it still does not seem to work, please share a reproduction repository so we can look into this issue. Without a reproduction, this will be near impossible to resolve.

**Comment by NicoP-S** [comment] 2021-12-09 10:22
I have the same problem. Using quasar with npm and capacitor.
like @mozolev i get `BarcodeScannerWeb `  and the error `Error: method not available in web`

![image](https://user-images.githubusercontent.com/8988747/145376923-2ef41a10-9fcd-47b0-9383-db6074c1c968.png)

I created a test repo: https://github.com/NicoP-S/barcodescan/blob/master/src/pages/Native.vue
after clone run
```
npm install
quasar dev -m capacitor -T android
```
Then android should be started --> start emulator
I am new to capacitor so it could be that i missing anything...

**Comment by jehadja** [comment] 2022-01-30 08:16
@NicoP-S Hi,
mostly you are using documentation for the new version to implement the old version 
you are using capacitor v2 
https://github.com/NicoP-S/barcodescan/blob/master/src-capacitor/package.json#L11

so you need to use this documentation
https://github.com/capacitor-community/barcode-scanner/tree/release/v1.3.0


fast fix steps need to do 
```
 npm i @capacitor-community/barcode-scanner@1.2.1
 npx cap sync
```
 in your main activity
```
 import com.dutchconcepts.capacitor.barcodescanner.BarcodeScanner;
            add(BarcodeScanner.class);
```
the calling of BarcodeScanner is not as v3 
instead of
`import { BarcodeScanner } from '@capacitor-community/barcode-scanner';
`
use 
```
 import { Plugins } from "@capacitor/core";
    async startScan() {
      const { BarcodeScanner } = Plugins;
      const prem = await this.didUserGrantPermission();
      if (prem) {
        BarcodeScanner.hideBackground();
        const result = await BarcodeScanner.startScan();
        if (result.hasContent) {
          console.log(result.content);
        }
      } else {
      }
    },

```

**Comment by thegnuu** [comment] 2022-02-27 14:22
Unfortunately I am currently not able to reproduce this issue, do you guys still have issues using this plugin?

If so, it would be nice to have a repo to reproduce your issues, otherwise it will be really hard for me to find something...

**Comment by thegnuu** [comment] 2022-03-01 13:55
I am closing this issue now since I am cleaning up "old" issues, if you still run into trouble feel free to reopen it :)

**Closed by thegnuu** 2022-03-01 13:55 UTC
