### ISSUE TITLE
iOS devices heating up

### ISSUE THREAD

**Issue by caginneocles** [capacitor-community/barcode-scanner#163] opened 2022-09-30 07:16 UTC
**Description**
We are using the plugin for scanning barcodes. Usually it is used in warehouses. We noticed that after a couple of minutes the camera and eventually the device itself get heated up and it is very obvious. You can feel it is overheated after five minutes. Although I never experienced it is reported that sometimes it ends up with application crashing. 

It is very obvious on iPhone X and iPhone Xr. It is also observable in iPhone SE (2020) devices.

I forked the repo and changed discoverCaptureDevices function only to have builtInWideAngleCamera by changing the line to this:
`return AVCaptureDevice.DiscoverySession(deviceTypes: [ .builtInWideAngleCamera ], mediaType: .video, position: .unspecified).devices`
from this:
`return AVCaptureDevice.DiscoverySession(deviceTypes: [.builtInTripleCamera, .builtInDualCamera, .builtInTelephotoCamera, .builtInTrueDepthCamera, .builtInUltraWideCamera, .builtInDualWideCamera, .builtInWideAngleCamera], mediaType: .video, position: .unspecified).devices`

I thought opening triple camera for simple barcode reading may be unnecessary and that is the reason why device was heating up. But it didn't help.

Our app is a replacement of an old NativeScript app and that app doesn't have this problem on barcode scanning. I tried some other Cordova/Phonegap plugins. Most of them has this issue except one. We are in no position of switching plugins right now. I wonder if there are any solutions to fix this issue or if I misconfigured something.

**Steps to reproduce**
1. Open the camera
2. Leave the device for 5 minutes
3. Check the camera with your hand. Observe it is heated up
4. Leave for another 10 minutes
5. Check the whole device is heated up.

**Comment by thegnuu** [comment] 2022-09-30 07:29
Unfortunately this is nearly impossible for me to reproduce since I don't have an "older" device to test it with. Personally I don't think that this is an easy fix. The only possible solution I can think of right now is to lower the capture fps and resolution, but this will generate way worse results (especially with 1D codes).

I guess the "overheating" is linked to AVFoundation, but I am not sure what element causes this issue. I think the source might be the `AVCaptureMetadataOutputObjectsDelegate` which can cause big loads and use a lot of calculation power on devices with older CPUs.

I have a branch "ready" for iOS which uses `mlkit`. Since this is using another method to detect codes and only uses the camera output, not the metadata capturing, this might lead to better results (or worse ones, really hard to say for me).

Are you willing to give this branch a try with one of your iPhone X? The interfaces changed a bit, but it should be quite easy to create a test-setup with this.

**Comment by caginneocles** [comment] 2022-09-30 09:07
Sure thing. I can test the branch in a week. I assume setting up will be rather quick just to test this issue.

**Comment by thegnuu** [comment] 2022-09-30 09:14
It should yes, you can just add the branch to your `package.json` and change the calls according to the interfaces (there is no more single-scan function) just a `start`, `pause`, `resume` and `stop`.

https://github.com/capacitor-community/barcode-scanner/blob/ml-kit/src/definitions.ts

It is not finished, for example checking the permissions aso. is missing, but it should work in general for this testing purpose.

**Comment by caginneocles** [comment] 2022-10-31 08:43
Hi, it is indeed not heating up on this branch. Also ability to get media devices and passing the stream to a `video` element is very beneficial compared to previous solution.

I somehow figured the permissions from a closed issue but couldn't make it work fully. It sometimes doesn't read at all, or reads one barcode and stops reading. Maybe I need to make more changes for it to read barcodes continuously. When do you think this branch will be production ready?

**Comment by thegnuu** [comment] 2022-11-01 10:15
Sounds good! Someone is currently working on the android part of the plugin, unfortunately I don't have a timeline right now.

The main permission issues were on android as far as I know, so I guess fixing the permission on iOS will not be a big issue.

**Comment by thegnuu** [comment] 2022-11-24 09:33
I was now able to merge the android version into the branch, this is a big step for the ml-kit version.

I still needs cleanup and my time is kinda limited at the moment unfortunately, but I will do my best to make progress as fast as possible.

**Comment by caginneocles** [comment] 2023-01-11 12:36
Hi, after receiving some complaints of how the version in main branch gets laggy after using the scanner 5 to 40 minutes I wanted to give ml-kit branch another shot. And now I can reproduce the heating on my iphone X after using 7 minutes.
Can it be that some of your recent commits in November started to cause this issue again?

**Comment by caginneocles** [comment] 2023-01-11 13:00
Yes, I tested the recent changes on `ml-kit` branch. 

After ml-kit branch also heated up I tried to put camera stream into a video object by using `navigator.mediaDevices.getUserMedia` and it doesn't read barcodes at all. This happens on `main` branch as well

Also on ml-kit branch, without video object, it stops reading after a couple of times. And the camera gets frozen. Maybe it's because it's under development and it's a known issue.

**Comment by thegnuu** [comment] 2023-01-11 13:17
I am not sure about it, my changes might cause additional overhead there at the moment, but IMHO it should not be that big of an impact.

The problem is that I have no "older" devices to test with, I just have my 14 pro... And I am not able to reproduce the performance/heating up issue so far, the problems might also be related to some iOS updates, if the issues occur without my recent changes as well.

**Comment by thegnuu** [comment] 2023-05-08 14:55
I will close this since I am still not able to reproduce it. I just released `v5.0.0-beta.1` which uses `ml-kit`. Feel free to test it with this implementation :)

**Closed by thegnuu** 2023-05-08 14:55 UTC
