### ISSUE TITLE
Error lunch web - not implemented on web

### ISSUE THREAD

**Issue by achacofe** [capacitor-community/barcode-scanner#113] opened 2022-03-30 06:53 UTC
**Describe the bug**
It says that it is compatible for all three platforms, but I don't understand how I can make it work on the web, I have tried downloading the project itself and launching it but there is no way, it gives me this error:

```
core.mjs:6484
ERROR Error: Uncaught (in promise): Error: Not implemented on web.
Error: Not implemented on web.
    at BarcodeScannerWeb.unimplemented (index.js:376:16)
    at web.js:7:20
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1349:1)
    at asyncToGenerator.js:21:1
    at BarcodeScannerWeb.hideBackground (web.js:6:28)
    at index.js:196:35
    at resolvePromise (zone.js:1262:1)
    at resolvePromise (zone.js:1216:1)
    at zone.js:1329:1
    at _ZoneDelegate.push.3279._ZoneDelegate.invokeTask (zone.js:443:1)
    at Object.onInvokeTask (core.mjs:25463:33)
    at _ZoneDelegate.push.3279._ZoneDelegate.invokeTask (zone.js:442:1)
    at Zone.push.3279.Zone.runTask (zone.js:214:1)
    at drainMicroTaskQueue (zone.js:632:1)
```

**To Reproduce**

1. Go to BarCodeScanner
2. Click on Scan
3. See error

**Expected behavior**
I hope that clicking the Scan button will open the camera on the desktop or laptop screen.

**Screenshots**
App:

![Captura de Pantalla 2022-03-30 a las 8 18 59](https://user-images.githubusercontent.com/98405076/160766781-acfebf08-1643-461e-b98f-7e2989223a5f.png)

Package.json:
![Captura de Pantalla 2022-03-30 a las 8 39 43](https://user-images.githubusercontent.com/98405076/160767595-2cc8ac08-d246-4d32-a067-4f9b3995186b.png)

Implementation method:
![Captura de Pantalla 2022-03-30 a las 8 40 42](https://user-images.githubusercontent.com/98405076/160767717-000ec428-290e-40f7-ac14-daa487fd1ebb.png)

**Version**
v2.1.0

**Desktop (please complete the following information):**

- OS: macOS Monterey Versión 12.3 (21E230)
- Browser Chrome Versión 99.0.4844.84 (Build oficial) (x86_64)

**Comment by tafelnl** [comment] 2022-03-30 08:11
Unfortunately no support for web has been added yet. Closing as a duplicate of #31

**Closed by tafelnl** 2022-03-30 08:11 UTC

**Comment by achacofe** [comment] 2022-03-30 08:49
@tafelnl Thank you very much for the clarification. Could you point me to a scanner plugin for BarCodes, QR, etc. that has support for Web, Android and iOS?
