### ISSUE TITLE
Add Support for Capacitor 3

### ISSUE THREAD

**Issue by phoenix503** [capacitor-community/barcode-scanner#39] opened 2021-05-28 07:09 UTC
**Describe the bug**
`Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0:`

**To Reproduce**

Add same package to any project and try doing ng build
after 
npx cap sync
npx cap open ios
Run Project a error will come as above

- OS: iOS
- Version 14

**Comment by tafelnl** [comment] 2021-05-28 07:26
Duplicate of #23

**Closed by tafelnl** 2021-05-28 07:26 UTC
