### ISSUE TITLE
 Error: “BarcodeScanner.checkPermission()” is not implemented on android 

### ISSUE THREAD

**Issue by Mgoumane** [capacitor-community/barcode-scanner#221] opened 2023-04-07 14:47 UTC
Hello everyone ! I am using the @capacitor-community/barcode-scanner and when i test the scanner in android studio, i get this error :

E/Capacitor/Console: File: http://localhost/main.6ddbf702db8bc9b1.js - Line 1 - Msg: ERROR Error: Uncaught (in promise): Error: “BarcodeScanner.checkPermission()” is not implemented on android
Error: “BarcodeScanner.checkPermission()” is not implemented on android
at http://localhost/7423.28d442c0482fb5bc.js:1:2292
at v.invoke (http://localhost/polyfills.fc6fad8ce607b49d.js:1:6542)
at Object.onInvoke (http://localhost/main.6ddbf702db8bc9b1.js:1:251927)
at v.invoke (http://localhost/polyfills.fc6fad8ce607b49d.js:1:6482)
at M.run (http://localhost/polyfills.fc6fad8ce607b49d.js:1:1938)
at http://localhost/polyfills.fc6fad8ce607b49d.js:1:16761
at v.invokeTask (http://localhost/polyfills.fc6fad8ce607b49d.js:1:7160)
at Object.onInvokeTask (http://localhost/main.6ddbf702db8bc9b1.js:1:251743)
at v.invokeTask (http://localhost/polyfills.fc6fad8ce607b49d.js:1:7081)
at M.runTask (http://localhost/polyfills.fc6fad8ce607b49d.js:1:2555)

**Comment by thegnuu** [comment] 2023-04-08 14:10
@Mgoumane this is usually not an issue with the plugin itself, but it might happen with an inproper capacitor setup.

Unfortunately it is hard so say what exactly is going on without a repo to reproduce it. Can you eventually share your repo?

**Comment by thegnuu** [comment] 2023-05-08 14:42
I will close this issues since I have not gotten any feedback until now.

**Closed by thegnuu** 2023-05-08 14:42 UTC

**Comment by ukaleem** [comment] 2023-07-19 23:05
<img width="1240" alt="Screenshot 2023-07-20 at 4 02 39 AM" src="https://github.com/capacitor-community/barcode-scanner/assets/39130173/92e7e6d2-186e-4718-b185-8ecb4efbefc4">
Having the same issue !

**Comment by ukaleem** [comment] 2023-07-20 09:23
> Hello everyone ! I am using the @capacitor-community/barcode-scanner and when i test the scanner in android studio, i get this error :
> 
> E/Capacitor/Console: File: http://localhost/main.6ddbf702db8bc9b1.js - Line 1 - Msg: ERROR Error: Uncaught (in promise): Error: “BarcodeScanner.checkPermission()” is not implemented on android Error: “BarcodeScanner.checkPermission()” is not implemented on android at http://localhost/7423.28d442c0482fb5bc.js:1:2292 at v.invoke (http://localhost/polyfills.fc6fad8ce607b49d.js:1:6542) at Object.onInvoke (http://localhost/main.6ddbf702db8bc9b1.js:1:251927) at v.invoke (http://localhost/polyfills.fc6fad8ce607b49d.js:1:6482) at M.run (http://localhost/polyfills.fc6fad8ce607b49d.js:1:1938) at http://localhost/polyfills.fc6fad8ce607b49d.js:1:16761 at v.invokeTask (http://localhost/polyfills.fc6fad8ce607b49d.js:1:7160) at Object.onInvokeTask (http://localhost/main.6ddbf702db8bc9b1.js:1:251743) at v.invokeTask (http://localhost/polyfills.fc6fad8ce607b49d.js:1:7081) at M.runTask (http://localhost/polyfills.fc6fad8ce607b49d.js:1:2555)

Did you find some fix?

**Comment by kacangdankawan** [comment] 2023-07-31 03:08
I also having the same problem when running on android studio

`[Barcode Scanner error: Error: BarcodeScanner.checkPermission() is not implemented on android]`

However , it works well on webview via ionic serve.

*I have disable the checkpermission() line , but it comes out with new error for scan

`Sending plugin error: {"save":false,"callbackId":"4461136","pluginId":"BarcodeScanner","methodName":"startScan","success":false,"error":{"message":"Attempt to invoke virtual method 'void androidx.camera.view.PreviewView.setScaleType(androidx.camera.view.PreviewView$ScaleType)' on a null object reference"}}`

**Comment by ukaleem** [comment] 2023-07-31 10:31
I still find no success!

**Comment by lzbaumgart** [comment] 2023-08-16 02:21
I have the same issue. I already removed the checkPermission(), and now throws with hideBackground method. Im trying to downgrande my capacitor version.

**Comment by WilsonHuallpa** [comment] 2023-11-24 19:36
También tengo el mismo problema cuando ejecuto Android Studio.

[Barcode Scanner error: Error: BarcodeScanner.checkPermission() is not implemented on android]. ¿alguno pudo solucionarlo?
