### ISSUE TITLE
Plugin example in ionic/angular project

### ISSUE THREAD

**Issue by fseve** [capacitor-community/barcode-scanner#20] opened 2021-02-28 20:22 UTC
**Describe the bug**

First of all thank you very much for the work you do for the community

I have been trying to integrate this plugin into a basic ionic v5 project, but have had some trouble getting the scanner to work.

The error that appears when I try it on an Android device is:

Error: Uncaught (in promise): Error: method not available in web Error: method not available in web

**To Reproduce**

1. Create ionic project: ionic start
2. Install plugin
3. Add android platform
4. Run on android device

**Expected behavior**
Barcode scanner plugin working in ionic or example

**Version**
Ionic v5 
Plugin v1.1.1

- OS: Android 9.0
- Device: Xiaomi Redmi Note 5

![image](https://user-images.githubusercontent.com/19912797/109432347-b0bceb80-79d8-11eb-83c4-baf9df861ea8.png)

**Comment by tafelnl** [comment] 2021-03-01 12:24
It seems like you are trying to use the plugin in a browser.

Do you have your app installed as an app (e.g. an .apk file) or are you debugging it in the browser?

**Comment by fseve** [comment] 2021-03-01 19:00
I use the command `ionic cap run android -l --external` that I found on the page of capacitor...

https://capacitorjs.com/docs/guides/live-reload


The application is installed on my phone and I get the error that I mention above

**Comment by tafelnl** [comment] 2021-03-01 22:10
Would you be able to provide a screenshot and ideally a reproduction code snippet/repo?

**Comment by fseve** [comment] 2021-03-01 22:58
Yes of course. I just uploaded my code to github, any help is important to me

https://github.com/fseve/test-capacitor-barcode

Thanks

**Comment by tafelnl** [comment] 2021-03-02 09:29
Make sure you follow the steps under [installation](https://github.com/capacitor-community/barcode-scanner#installation) and [configuration](https://github.com/capacitor-community/barcode-scanner#installation) in de readme

I see that you are missing the `add(BarcodeScanner.class);` line for example.

Also make sure you either run something like `npm run ng build && npx cap copy`. That will build your project and copy the files to the right directory.

If you want to use live reload, you should make sure that in the `capacitor.config.json` file, the `server` variable is set correctly. It should look something like this:

```json
"server": {
  "url": "http://192.168.1.68:8100",
  "cleartext": true
},
```

**Comment by fseve** [comment] 2021-03-02 15:36
Hello, first of all, I apologize for the inconvenience caused, I appreciate your help.

I have made the changes you recommended and the errors from before do not appear, but the camera does not open and I can never see the scanner, however I do not find errors that give me any idea about what is happening.


Again thank you very much, the problem is not the plugin, but the ignorance of how to use it in an ionic application, I am new to capacitor, I used cordova before and now I am learning capacitor.

**Comment by SalahAdDin** [comment] 2021-03-03 07:01
> Hello, first of all, I apologize for the inconvenience caused, I appreciate your help.
> 
> I have made the changes you recommended and the errors from before do not appear, but the camera does not open and I can never see the scanner, however I do not find errors that give me any idea about what is happening.
> 
> Again thank you very much, the problem is not the plugin, but the ignorance of how to use it in an ionic application, I am new to capacitor, I used cordova before and now I am learning capacitor.

Don't feel bad friend, i am having the same error here and i quite implemented many other plugins(most of them from community) before to test this. I'm also lost about why we can see the scanner.

**Comment by tafelnl** [comment] 2021-03-03 07:19
It looks like you are having an issue with hiding the background. Please see this thread: https://github.com/capacitor-community/barcode-scanner/issues/7#issuecomment-744441148

But since this is another issue than the one mentioned here first I will close this one. If you still experience an issue after reading #7, please do not hesitate to open up a new one.

**Closed by tafelnl** 2021-03-03 07:19 UTC
Labels: needs reply
