### ISSUE TITLE
I would like to contribute to the project

### ISSUE THREAD

**Issue by tomfong** [capacitor-community/barcode-scanner#127] opened 2022-05-27 01:55 UTC
I love this project and I'm using it in my FOSS app (https://github.com/tomfong/simple-qr).

I would like to contribute to the project and help maintain the plugin especially the Android version, but I am a newbie of capacitor plugin and even know nothing about Swift.

Could you tell me the steps where I should start?

**Comment by tomfong** [comment] 2022-05-30 08:14
Thanks for your reply and help!

**Comment by corpro** [comment] 2022-06-04 21:52
Very impressed with your project and would like to take it to the next level.  I want it to scan as fast as this app 
https://apps.apple.com/app/qr-code-barcode-scanner/id1048473097

Could you tell me the steps where I should start?

**Comment by thegnuu** [comment] 2022-06-07 11:00
Hard to say since I have no idea what libs this project relies on. One idea I have in mind is #107 which might provide better and faster results. Unfortunately I currently have not much time to spend and investigate this implementation....

**Comment by corpro** [comment] 2022-06-08 19:27
Don't capture input at the camera’s native resolution seems like the key to performance.

**Comment by thegnuu** [comment] 2022-06-08 20:09
It's pretty easy to play around with the resolution if you plan to read 2D codes, since most of them are "built" to be read by cameras and will work with missing information for example caused by a lower resolution. It's a completely different story if you want to more or less properly support 1D codes.

Finding a proper balance between resolution, performance and usable results is quite difficult, but if you think you can provide changes which will improve the results and performance with the current implementation that would be awesome :) Currently I cannot see much room for improvement without using other libs and tools like ML Kit...

**Comment by thegnuu** [comment] 2022-06-15 13:14
Sure, you can find my email address on my GitHub profile...

**Comment by thegnuu** [comment] 2022-11-24 12:08
@tomfong I will close this issue :)

**Closed by thegnuu** 2022-11-24 12:08 UTC
