### ISSUE TITLE
Android 32 No Camera shown or error logs

### ISSUE THREAD

**Issue by tigohenryschultz** [capacitor-community/barcode-scanner#186] opened 2023-01-06 21:47 UTC
**Describe the bug**
Nothing happens when invoking the startScan promise

I've followed all the examples to display/set transparency and tried every example in the multiple issues explaining this problem. None work. the startScan promise never resolves and throws no logs(why)? There are no dom elements created, and if they were shouldn't it  have a unique ID? Am I supposed to add an element to my page for the camera? Does anyone have this plugin working with new Capacitor 4/Ionic 6/Android 32?

**To Reproduce**
Copy and paste examples from this page and doesn't work.

**Expected behavior**
Camera pops up

**Screenshots**

**Version**
3.0.1

**Desktop (please complete the following information):**

Ionic:

   Ionic CLI       : 6.19.0 (C:\Users\Henry\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.4.1

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.0
   OS     : Windows 10

**Smartphone (please complete the following information):**

- Device: Android S 21+
- OS: Android 32
- Browser Ionic

**Additional context**

**Comment by thegnuu** [comment] 2023-01-10 14:44
The plugin works on my devices with exactly the same setup, there will not be any element added to the DOM, since the cam is rendered behind the DOM.

Unfortunately I will most likely not be able to help you without a repo that helps me to reproduce your issue on my end.

**Comment by thegnuu** [comment] 2023-02-23 09:14
Since I have not heard anything from your end I will close this issue for now, feel free to reopen it and provide additional info if you still have issues!

**Closed by thegnuu** 2023-02-23 09:14 UTC
