### ISSUE TITLE
Code 39 scanning is extremely slow on iOS

### ISSUE THREAD

**Issue by sephallen** [capacitor-community/barcode-scanner#104] opened 2022-02-22 12:06 UTC
**Describe the bug**
Code 39 barcode scanning is very slow on iOS - typically taking around 15+ seconds to scan.
I do not believe this issue to be specific to this plugin as it also happens with https://github.com/phonegap/phonegap-plugin-barcodescanner and https://github.com/bitpay/cordova-plugin-qrscanner. I have forked the latter to work with Capacitor 3 and support Code 39 barcodes which can be found here: https://github.com/beholdio/cordova-plugin-qrscanner.

To rule out that is was an issue with my project, I also tested this example project: https://github.com/enappd/ionic-capacitor-barcode-scanner (which uses phonegap-plugin-barcodescanner) but the problem exists there too. To test this example project, I needed to update Capacitor core and iOS to version 2 in order to build it.

I also tested Ionic 6 without Capacitor (again using phonegap-plugin-barcodescanner) and this also has the same issue.

However, in a legacy Ionic 3 project I support, which uses cordova-plugin-qrscanner, it scans Code 39 much faster on the exact same iPhone hardware.

The common denominator here is Ionic 6, so perhaps this is more of an issue for the Ionic team, but I thought I'd check here first.

**To Reproduce**
Steps to reproduce the behaviour:

1. Attempt to scan any Code 39 barcode on iOS.

**Expected behaviour**
The scanning to be much faster.

**Version**
v2.0.1

**Smartphone (please complete the following information):**

- Device: iPhone 7
- OS: iOS 15.2.1
- Browser Safari

**Comment by thegnuu** [comment] 2022-02-25 13:08
Since the library is using other libraries to do the "real" work (AVFoundation on iOS and zxing on Android) I am not sure if there is much we can do here. 2D Barcodes are not really designed to be scanned by a camera so reading those codes based on an image is harder than scanning for example a QR code.

I am new maintainer of this library and need to check it out first, maybe there are some ways to get better results for 2D codes, but I cannot promise a better behaviour on this one :)

**Comment by sephallen** [comment] 2022-02-25 15:29
@thegnuu much appreciated! I'll keep looking for solutions elsewhere and I will report back if I find anything. The curious part is that other plugins utilising AVFoundation on Ionic 3 don't appear to be affected which leads me to believe that this may be more of an Ionic 5+ issue.

**Comment by thegnuu** [comment] 2022-02-25 15:34
It might absolutely be possible that there is an issue somewhere! As I said, I just started helping out here and right now I am not really familiar with the code. If you can find an example which works better for you, it would be great if you let me know. 

Way easier to find something with a properly working example, at least if the issue is somehow related to the AVFoundation implementation ;) I have not checked the recognition times on android by now, i will spend a few hours next week on this project and I will have an initial look at this one as well.

**Comment by thegnuu** [comment] 2022-02-27 14:45
@sephallen I created a single issue to keep track of the 1D performance and will close this one :)

**Closed by thegnuu** 2022-02-27 14:45 UTC
Labels: enhancement, priority-2
