### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by EvaKrizal** [capacitor-community/barcode-scanner#166] opened 2022-10-30 17:18 UTC
When using in project, we were not able to get the scanner working due to errors: ACCESS DENIED...

1. Implement in app
2. Try to scan a qr code
3. See error

Expected: camera would open and user would be able to scan qr code.

![Screenshot 2022-10-24 at 14 33 04](https://user-images.githubusercontent.com/91963615/198892015-5cf7ddae-1572-44f7-b36c-891e7148a2ef.jpeg)

**Version**
Capacitor version 4.3

- Device:Xiaomi mi 8
- Android 10

**Comment by thegnuu** [comment] 2022-10-31 10:30
Did you set the permissions as described?
https://github.com/capacitor-community/barcode-scanner#android

**Comment by EvaKrizal** [comment] 2022-10-31 10:58
Yes, all was implemented according to instruction.

**Comment by thegnuu** [comment] 2022-11-01 10:20
Unfortunately I won't be able to help you without a working (or in this case not working) example repo.

I had a look at my test environments and I am not able to reproduce your issue...

**Comment by pdarcy97** [comment] 2022-11-02 12:04
Also facing this issue and have been unable to find a workaround

Version
Capacitor version 4.3

Device: OnePlus 8 Pro
Android 12

**Comment by thegnuu** [comment] 2022-11-18 09:57
As I said I believe this is an issue with the setup, and I am unable to help without a way to reproduce your issues...

I am closing this since I have not gotten any feedback, feel free to reopen it if you still have issues and you can provide a repo to help you out!

**Closed by thegnuu** 2022-11-18 09:57 UTC
